crm_call/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('user_auth.urls')),
    path('',  include('leads.urls')),
    path('',  include('home.urls')),
    path('',  include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name="home"),
    path('setting/', views.companySetting, name="company_setting"),
    path('stage/add/', views.addStage, name="add_new_satge_for_leads"),
    path('stage/delete/<int:stage_pk>/', views.deleteStage,
         name="delete_stage"),
    path('stage-order/update/', views.updateStageOrder,
         name="update_stage_order"),
    path('move-stage-lead/', views.moveStageLead, name="move_stage_lead"),
    path('custom/field/create/', views.createCustomField,
         name="create_custom_field"),


    # API releted
    path('api/setting/', views.apiCompanySetting),
]

leads/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from home.models import CustomField, LeadStage
from users.models import Company


class Lead(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    stage = models.ForeignKey(LeadStage, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    lead_api_key = models.CharField(max_length=50, default=uuid.uuid4())
    contact_person = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    designation = models.CharField(max_length=50, blank=True)
    source = models.CharField(max_length=50, blank=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Custom field answer for leads
class CustomFieldAnswer(models.Model):
    custum_field = models.ForeignKey(CustomField, on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, on_delete=models.SET_NULL, null=True)
    title_answer = models.CharField(max_length=250)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.custum_field.field_title}-answer'


class LeadContact(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    contact_person = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    designation = models.CharField(max_length=50, blank=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.contact_person


class LeadNote(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    note = models.TextField()

    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class LeadTask(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    task = models.TextField()

    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class LeadProfileLog(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    log = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.lead.title + '-Log-' + str(self.id)

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class Company(models.Model):
    super_admin = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True)

    company_name = models.CharField(max_length=200)
    api_key = models.CharField(max_length=50, default=uuid.uuid4())
    phone = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=50, blank=True)
    logo = models.ImageField(
        upload_to='company_logo/', default="default/dummy-logo.jpeg",)

    # to store logic for rendering the stage
    stage_reorder_logic = models.TextField(blank=True)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name


class UserProfile(models.Model):
    USERTYPE = (
        ('0', 'Super Admin'),
        ('1', 'Manager'),
        ('2', 'Normal User'),
        ('3', 'type-3'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    profile_pic = models.ImageField(
        upload_to='profile_pic/', default="default/profile-dum.jpg")

    user_type = models.CharField(max_length=50, choices=USERTYPE, blank=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.user.first_name:
            return self.user.first_name + ' ' + self.user.last_name
        return str(self.id)

    @property
    def full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

home/forms.py
from home.models import CustomField
from django import forms


class AddCustomFieldForm(forms.ModelForm):
    class Meta:
        model = CustomField
        fields = ['field_title', 'field_type']

        widgets = {
            'field_title': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
            }),
            'field_type': forms.Select(attrs={
                'class': "form-control",
            }),
        }

home/views.py
import json
import uuid

from django.core.serializers import serialize
from django.http.response import HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.models import User

from leads.models import Lead
from users.models import Company, UserProfile

from .forms import AddCustomFieldForm
from .models import CustomField, CustomFieldChoise, LeadStage
# from .gmail_api import syncGmailAPI
from .utils import sortQueryObj


@login_required(login_url='login')
def homePage(request, api_key=None):
    user = request.user
    loggedInUser = UserProfile.objects.get(user=user)

    # service = syncGmailAPI(user)
    # print("credssss: ", service)
    randomStr = uuid.uuid4()
    print("randomStr: ", len(str(randomStr)), '-', randomStr)
    context = {
        "loggedInUser": loggedInUser,
    }
    return render(request, 'home/home_page.html', context)


@login_required(login_url='login')
def companySetting(request):
    loggedInUser = UserProfile.objects.get(user=request.user)
    company = loggedInUser.company
    stages = LeadStage.objects.filter(company=company)

    # orderIndexObj, created = StageIndexOrder.objects.get_or_create(
    #     company=company)

    # orderIndexList = []
    # if not created:
    #     orderIndexList = orderIndexObj.reorder_string.split(',')
    # sortedStages = sortQueryObj(stages, orderIndexList)

    stageReorderLogic = company.stage_reorder_logic
    # print("stageReorderLogic: ", stageReorderLogic)
    if stageReorderLogic.strip() != '':
        sortedStages = sortQueryObj(stages, stageReorderLogic.split(','))
    else:
        sortedStages = []

    # print("sortedStages: ", sortedStages)

    customFields = CustomField.objects.filter(company=company)

    context = {
        "sortedStages": sortedStages,
        "loggedInUser": loggedInUser,
        "custom_field_form": AddCustomFieldForm(),
        "customFields": customFields,
    }
    return render(request, 'home/company_setting_page.html', context)


# Adding stages for lead in company setting page
@login_required(login_url='login')
def addStage(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        newStageObj = LeadStage.objects.create(
            company=company,
            stage_label=request.POST['new_lead_stage'],
            added_by=request.user,
        )

        stageReorderLogic = company.stage_reorder_logic
        if stageReorderLogic.strip() == '':
            company.stage_reorder_logic = str(newStageObj.id)
        else:
            company.stage_reorder_logic = f"{stageReorderLogic},{str(newStageObj.id)}"
        company.save()

        return redirect('company_setting')


# Updating order of stages in company setting page whem dragged
@login_required(login_url='login')
def updateStageOrder(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        stageReorderLogic = company.stage_reorder_logic

        data = json.loads(request.body)
        draggedItemId = data['draggedItemId']
        oldIndexItem = data['oldIndexItem']
        newIndexItem = data['newIndexItem']

        # Split string by comma
        orderList = stageReorderLogic.split(',')
        # print("orderList1: ", orderList)

        # Delete old index of dragged element
        del orderList[oldIndexItem]
        # print("orderList2: ", orderList)

        # Add dragged element to new index
        orderList.insert(newIndexItem, draggedItemId)
        # print("orderList3: ", orderList)
        newStr = ",".join(orderList)
        # print("new str: ", newStr)

        company.stage_reorder_logic = newStr
        company.save()

        return JsonResponse({"msg": "success"})


# Delete stage from settings if there is no leads in the stage
@login_required(login_url='login')
def deleteStage(request, stage_pk):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        stageReorderLogic = company.stage_reorder_logic

        stage = get_object_or_404(LeadStage, id=stage_pk)
        if company != stage.company:
            return HttpResponseForbidden()

        leadsReorderLogic = stage.leads_reorder_logic

        # check, if there is any leads in this stage
        if leadsReorderLogic.strip() == '':
            stage.delete()

            logicOrderStrList = stageReorderLogic.split(',')
            # print("logicOrderStrList: ", logicOrderStrList)

            logicOrderStrList.remove(str(stage_pk))
            # print(logicOrderStrList)

            newStageReorderLogic = ",".join(logicOrderStrList)
            # print("newStrOrder: ", newStrOrder)

            company.stage_reorder_logic = newStageReorderLogic
            company.save()

            return JsonResponse({
                "success": True,
                "msg": "Successfully deleted!!",
            })
        else:
            return JsonResponse({
                "success": False,
                "msg": "Can't delete this stage. Please move all the leads" +
                " inside of this stage and try again."
            })


# Move leads from one stage to another stage
@login_required(login_url='login')
def moveStageLead(request):
    if request.method == 'POST':
        company = UserProfile.objects.get(user=request.user).company

        movedFrom = request.POST.get('stage_moved_from')
        movedTo = request.POST.get('stage_moved_to')
        # print(movedFrom, '-', movedTo)

        movedFromStage = LeadStage.objects.get(id=movedFrom)
        # Update status of all the leads which are moved
        movedToStage = LeadStage.objects.get(id=movedTo)
        # print(newStage.stage_label)

        if company != movedFromStage.company:
            return HttpResponseForbidden()

        movedFromLeadIds = movedFromStage.leads_reorder_logic
        movedToLeadIds = movedToStage.leads_reorder_logic

        # print(movedFromLeadIds, '-', movedToLeadIds)

        if movedFromLeadIds.strip() != '':
            leadIds = movedFromLeadIds.split(',')
            # print("leadIds: ", leadIds)

            for leadId in leadIds:
                newLead = get_object_or_404(Lead, id=leadId)
                newLead.stage = movedToStage
                newLead.save()
                # print("lead updated: ", newLead.stage.stage_label)
        else:
            return redirect('company_setting')

        # Move the order indexing from movedFrom to movedTo .
        if movedToLeadIds == '':
            movedToStage.leads_reorder_logic = movedFromLeadIds
        else:
            movedToStage.leads_reorder_logic = f"{movedToLeadIds},{movedFromLeadIds}"
        movedToStage.save()

        # empty the logic order of MovedFrom
        movedFromStage.leads_reorder_logic = ''
        movedFromStage.save()

        return redirect('company_setting')


@login_required(login_url='login')
def createCustomField(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        print(request.POST)
        extra_field_size = len(request.POST)-3
        print("extra_field_size: ", extra_field_size)

        if request.POST.get('field_type') == 'drop_down' or (
                request.POST.get('field_type') == 'drop_down'):
            if(extra_field_size <= 0):
                return redirect('company_setting')

        form = AddCustomFieldForm(request.POST)
        if form.is_valid():
            print("form Valid")
            customFieldObj = form.save(commit=False)
            customFieldObj.company = loggedInUser.company
            customFieldObj.save()

            if extra_field_size > 0:
                for index in range(extra_field_size):
                    option_choise = request.POST.get(f"option_{index}")
                    if option_choise:
                        CustomFieldChoise.objects.create(
                            custom_field=customFieldObj,
                            choise_name=option_choise,
                        )

        return redirect('company_setting')


# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
# ------------------------------------------APIS-----------------------------------------
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
def apiCompanySetting(request):
    api_key = request.GET.get('key')
    # print(api_key)

    if not api_key or len(api_key) < 36:
        return JsonResponse({
            "success": False,
            "msg": "Api Key is missing or invalid",
        }, status=400)

    try:
        company = Company.objects.get(api_key=api_key)
    except Company.DoesNotExist:
        return JsonResponse({
            "success": False,
            "msg": "invalid Key",
        }, status=404)

    stages = LeadStage.objects.filter(company=company)

    stageReorderLogic = company.stage_reorder_logic
    # print("stageReorderLogic: ", stageReorderLogic)
    if stageReorderLogic.strip() != '':
        sortedStages = sortQueryObj(stages, stageReorderLogic.split(','))
    else:
        sortedStages = []

    return JsonResponse({
        "success": True,
        "key": api_key,
        "stage": serialize('json', sortedStages)
    })

templates/home/agency_profile_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Company Profile</title>
{% endblock title %}

{% block breadcrumb_heading %}
Company Setting
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="#">Company Settings</a>
</li>
{% endblock breadcrumb %}

{% block page_content %}


<div class="row">
    <div class="col-lg-8 col-xlg-6 col-sm-10 mx-auto">
        <div class="card">
            <div class="card-body">
                <center>
                    <img src="{{userToAgency.agency.logo.url}}" class="rounded-circle" width="150">
                    <h4 class="card-title mt-2">{{userToAgency.agency.agency_name}}</h4>
                    <h6 class="card-subtitle">{{userToAgency.agency.city}}</h6>
                </center>
            </div>
            <div>
                <hr>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-4 col-xs-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.phone}}</p>
                    </div>
                    <div class="col-lg-4 col-xs-6 b-r">
                        <strong>Email</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.email}}</p>
                    </div>
                    <div class="col-lg-4 col-xs-6">
                        <strong>Address</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.address}}</p>
                    </div>
                </div>
                <div>
                    <hr>
                </div>
                <div class="row mt-2">
                    <div class="col-sm-12 col-lg-6">
                        <strong>View Other's Resume</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.all_resume_access_auth}}</p>
                    </div>
                    <div class="col-sm-12 col-lg-6">
                        <strong>Allow Recruiters to access all Jobs</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.recruiters_to_job_auth}}</p>
                    </div>

                    <div class="col-sm-12 col-lg-6">
                        <strong>Allow Recruiters to access all resume in Jobs</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.recruiters_to_resume_auth}}</p>
                    </div>

                    <div class="col-sm-12 col-lg-6">
                        <strong>Allow Franchise to access all resume in Jobs</strong>
                        <br>
                        <p class="text-muted">{{userToAgency.agency.franchise_to_resume_auth}}</p>
                    </div>
                </div>
                <div>
                    <hr>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-sm-12 b-r">
                        <strong>Resume Points</strong>
                        <br>
                        <span class="text-muted">{{userToAgency.agency.resume_point}}</span>
                        <button class="btn btn-sm btn-outline-success btn-rounded float-right" data-toggle="modal"
                            data-target="#buy_resume_point">
                            <i class="mdi mdi-plus-circle"></i> Buy More
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-footer p-4">
                <div class="row">
                    <div class="col-lg col-md">
                        <button class="btn btn-rounded btn-outline-warning float-right" data-toggle="modal"
                            data-target="#verticalcenter_update_agency">
                            <i class="fas fa-edit"></i>Update
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



<!-- Buy More Resume Point button modal content -->
<div id="buy_resume_point" class="modal" tabindex="-1" role="dialog" aria-labelledby="vcenter" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center bg-info">
                <h3 class="modal-title font-weight-bold text-white" id="vcenter">Buy Resume Point</h3>
                <button type="button" class="close text-danger" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form action="{% url 'add_resume_point' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_resume_point">Add Points</label>
                        <input class="form-control" type="number" name="resume_point" id="id_resume_point">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning waves-effect float-left"
                            data-dismiss="modal">Cancel</button>

                        <button type="submit" class="btn btn-danger waves-effect float-right">Confirm</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<!-- /.modal content -->




<!-- Update Agency Details button modal content -->
<div id="verticalcenter_update_agency" class="modal bs-example-modal-lg" tabindex="-1" role="dialog"
    aria-labelledby="vcenter" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center bg-dark text-white">
                <h3 class="modal-title font-weight-bold" id="vcenter">Update User Details</h3>
                <button type="button" class="close text-white" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form action="" method="post" enctype="multipart/form-data" class="form-horizontal form-material">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_agency_name" class="col-md-12">Company Name</label>
                            <div class="col-md-12">
                                {{form.agency_name}}
                            </div>
                        </div>

                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_email" class="col-md-12">Email</label>
                            <div class="col-md-12">
                                {{form.email}}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_phone" class="col-md-12">Phone</label>
                            <div class="col-md-12">
                                {{form.phone}}
                            </div>
                        </div>

                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_city" class="col-md-12">City </label>
                            <div class="col-md-12">
                                {{form.city}}
                            </div>
                        </div>

                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_address" class="col-md-12">Address </label>
                            <div class="col-md-12">
                                {{form.address}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-4 form-group">
                            <label for="id_profile_pic" class="col-md-12">Profile Pic
                                <span><img src="{{user.logo.url}}" class="rounded-circle" width="50"></span>
                            </label>

                            <div class="col-md-12">
                                <input type="file" name="logo" accept="image/*" id="id_logo" class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12 col-lg-6 form-group">
                            <label for="id_all_resume_access_auth" class="col-md-12">View Other's Resume </label>
                            <div class="col-md-12">
                                {{form.all_resume_access_auth}}
                            </div>
                        </div>

                        <div class="col-sm-12 col-lg-6 form-group">
                            <label for="id_recruiters_to_job_auth" class="col-md-12">Authorize Recruiters to view all
                                Jobs</label>
                            <div class="col-md-12">
                                {{form.recruiters_to_job_auth}}
                            </div>
                        </div>
                        <div class="col-sm-12 col-lg-6 form-group">
                            <label for="id_recruiters_to_resume_auth" class="col-md-12">Authorize Recruiters to view all
                                Resume in a Jobs</label>
                            <div class="col-md-12">
                                {{form.recruiters_to_resume_auth}}
                            </div>
                        </div>
                        <div class="col-sm-12 col-lg-6 form-group">
                            <label for="id_franchise_to_resume_auth" class="col-md-12">Authorize Franchises to view all
                                Resume in a Jobs</label>
                            <div class="col-md-12">
                                {{form.franchise_to_resume_auth}}
                            </div>
                        </div>
                    </div>

                    <!-- footer submit button -->

                    <div class="form-group d-flex justify-content-around text-center">
                        <div class="col-sm-6">
                            <button type="button" class="btn btn-warning waves-effect"
                                data-dismiss="modal">Cancel</button>
                        </div>
                        <div class="col-sm-6">
                            <button class="btn btn-success waves-effect">
                                <i class="mdi mdi-account-edit"></i>
                                <span> Update </span>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.modal content -->

<script>
</script>


{% endblock page_content %}

templates/home/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Dashboard</title>
{% endblock title %}

{% block breadcrumb_heading %}
Dashboard
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/">Dashboard</a>
</li>
{% endblock breadcrumb %}

{% block page_content %}
<div class="row mb-4">
    <div class="col-12">
        {% include 'home/home_comp/dashboard_mail.html' %}
    </div>
</div>

<div class="row">

    <div class="col-md-6 col-lg-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-uppercase">Active Clients</h5>
                <div class="d-flex align-items-center mb-2 mt-4">
                    <h2 class="mb-0 display-5"><i class="icon-people text-info"></i></h2>
                    <div class="ml-auto">
                        <h2 class="mb-0 display-6"><span class="font-normal">{{total_active_clients}}</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-lg-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-uppercase">Active Jobs</h5>
                <div class="d-flex align-items-center mb-2 mt-4">
                    <h2 class="mb-0 display-5"><i class="icon-folder text-primary"></i></h2>
                    <div class="ml-auto">
                        <h2 class="mb-0 display-6"><span class="font-normal">{{total_active_jobs}}</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-lg-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-uppercase">Franchises</h5>
                <div class="d-flex align-items-center mb-2 mt-4">
                    <h2 class="mb-0 display-5"><i class="icon-folder-alt text-danger"></i></h2>
                    <div class="ml-auto">
                        <h2 class="mb-0 display-6"><span class="font-normal">{{total_franchise}}</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-lg-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-uppercase">Total Resume</h5>
                <div class="d-flex align-items-center mb-2 mt-4">
                    <h2 class="mb-0 display-5"><i class="ti-file text-success"></i></h2>
                    <div class="ml-auto">
                        <h2 class="mb-0 display-6"><span class="font-normal">{{total_uploaded_resume}}</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock page_content %}