crm_call/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('user_auth.urls')),
    path('',  include('leads.urls')),
    path('',  include('home.urls')),
    path('',  include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name="home"),
    path('setting/', views.companySetting, name="company_setting"),
    path('stage/add/', views.addStage, name="add_new_satge_for_leads"),
    path('stage/delete/<int:stage_pk>/', views.deleteStage,
         name="delete_stage"),
    path('stage-order/update/', views.updateStageOrder,
         name="update_stage_order"),
    path('move-stage-lead/', views.moveStageLead, name="move_stage_lead"),
    path('custom/field/create/', views.createCustomField,
         name="create_custom_field"),


    # API releted
    path('api/setting/', views.apiCompanySetting),
]

leads/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('leads/', views.leadPage, name="leads_page"),
    path('lead/add/', views.addLead, name="add_lead"),
    path('lead/indexing/status/update/',
         views.updateLeadStatus, name="update_lead_status"),

    path('lead/<int:lead_pk>/', views.leadProfile, name="lead_profile"),
    path('lead/<int:lead_pk>/update/',
         views.updateLeadProfile, name="update_lead_profile"),

    path('lead/<int:lead_pk>/note/add/',
         views.addLeadNote, name="add_lead_note"),
    path('lead/<int:lead_pk>/task/add/',
         views.addLeadTask, name="add_lead_task"),

    path('lead/note/<int:lead_note_pk>/update/',
         views.updateLeadNote, name="update_lead_note"),
    path('lead/task/<int:lead_task_pk>/update/',
         views.updateLeadTask, name="update_lead_task"),

    path('lead/note/<int:lead_note_pk>/delete/',
         views.deleteLeadNote, name="delete_lead_note"),
    path('lead/task/<int:lead_task_pk>/delete/',
         views.deleteLeadTask, name="delete_lead_task"),

    # Inside lead profile
    path('lead/profile/status/update/',
         views.updateLeadStatusInProfile, name="update_lead_status_in_profile"),
]

leads/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from home.models import CustomField, LeadStage
from users.models import Company


class Lead(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    stage = models.ForeignKey(LeadStage, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    lead_api_key = models.CharField(max_length=50, default=uuid.uuid4())
    contact_person = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    designation = models.CharField(max_length=50, blank=True)
    source = models.CharField(max_length=50, blank=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Custom field answer for leads
class CustomFieldAnswer(models.Model):
    custum_field = models.ForeignKey(CustomField, on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, on_delete=models.SET_NULL, null=True)
    title_answer = models.CharField(max_length=250)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.custum_field.field_title}-answer'


class LeadContact(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    contact_person = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    designation = models.CharField(max_length=50, blank=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.contact_person


class LeadNote(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    note = models.TextField()

    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class LeadTask(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    task = models.TextField()

    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class LeadProfileLog(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    log = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.lead.title + '-Log-' + str(self.id)

leads/views.py
import json

from collections import defaultdict
# from django.core.serializers import serialize
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http.response import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render, redirect
# from django.shortcuts import get_object_or_404

from home.utils import sortQueryObj
from home.models import LeadStage
from users.models import UserProfile

from .forms import AddLeadForm
from .models import Lead, LeadNote, LeadTask, LeadProfileLog


# Lead Page
@login_required(login_url='login')
def leadPage(request):
    loggedInUser = get_object_or_404(
        UserProfile, user=request.user, is_deleted=False)
    company = loggedInUser.company

    stages = LeadStage.objects.filter(company=company)

    leads = Lead.objects.filter(company=company, is_deleted=False)

    # For displaying stages in sorted order
    stageReorderLogic = company.stage_reorder_logic
    orderIndexList = stageReorderLogic.split(',')

    sortedStages = sortQueryObj(stages, orderIndexList)

    # Logics For displaying item in respective stages in sorted manner
    leadsReorderLogicList = []
    for stageItem in stages:
        newLogicList = stageItem.leads_reorder_logic.split(',')

        # For listing all sorted index in a seperate stage fields
        newLogicObj = {}
        newLogicObj[stageItem.stage_label] = newLogicList
        leadsReorderLogicList.append(newLogicObj)

    # print("leadsReorderLogicList: ", leadsReorderLogicList)

    # a default dict, for displaying item in respective stages in sorted manner
    columnOrder = defaultdict(list)
    for leadsReorderLogic in leadsReorderLogicList:
        # print("leadsReorderLogic: ", leadsReorderLogic)
        for stage_label, leadIds in leadsReorderLogic.items():
            for leadId in leadIds:
                # print("leadId: ", leadId)

                if leadId != '':
                    newLeadObj = leads.filter(id=int(leadId)).first()
                    newStageLabel = newLeadObj.stage.stage_label
                    # print(type(newStageLabel), '-', newStageLabel)

                    columnOrder[newStageLabel].append(newLeadObj)

    # print("columnOrder: ", columnOrder)

    # # to iterate in default dict user dictName.items()
    # for x, y in columnOrder.items():
    #     print(type(x), '-', x)
    #     print(type(y), '-', y)

    context = {
        "loggedInUser": loggedInUser,
        "sortedStages": sortedStages,
        "columnOrder": columnOrder.items(),
    }

    return render(request, 'leads/leads_page.html', context)


@ login_required(login_url='login')
def addLead(request):
    loggedInUser = get_object_or_404(UserProfile, user=request.user)
    company = loggedInUser.company

    if request.method == 'POST':
        form = AddLeadForm(company, request.POST)
        if form.is_valid():
            newLeadObj = form.save(commit=False)
            newLeadObj.company = company
            newLeadObj.added_by = request.user
            newLeadObj.save()

            stage = newLeadObj.stage

            leadsReorderLogic = stage.leads_reorder_logic
            # if element_index_logic is empty or created for the first time
            if leadsReorderLogic == '':
                stage.leads_reorder_logic = str(newLeadObj.id)
            else:
                stage.leads_reorder_logic = \
                    f"{leadsReorderLogic},{str(newLeadObj.id)}"
            stage.save()

            # messages.success(request, 'Changes successfully saved.')
            return redirect('leads_page')

        else:
            form = AddLeadForm(company=company, initial={
                'stage': request.POST.get('stage'),
                'title': request.POST.get('title'),
                'contact_person': request.POST.get('contact_person'),
                'email': request.POST.get('email'),
                'phone': request.POST.get('phone'),
                'designation': request.POST.get('designation'),
                'source': request.POST.get('source'),
            })

            context = {
                "loggedInUser": loggedInUser,
                "form": form,
                "status": 400,  # for toaster
            }

            messages.add_message(
                request, messages.ERROR, 'Something went wrong.\
                    Please check all the fields and Try Again.'
            )
            return render(request, 'leads/add_lead.html', context)
    else:
        form = AddLeadForm(company=company)
        context = {
            "loggedInUser": loggedInUser,
            "form": form,
        }
        return render(request, 'leads/add_lead.html', context)


# Update leads stage status on leads page, when dragged
@login_required(login_url='login')
def updateLeadStatus(request):
    if request.method == 'POST':
        loggedInUser = get_object_or_404(
            UserProfile, user=request.user, is_deleted=False)

        data = json.loads(request.body)
        # print("data: ", data)

        lead_pk = data['terget_lead_pk']
        movedFromStagePk = data['moved_from_stage'].split('_')[-1]
        movedToStagePk = data['moved_to_stage'].split('_')[-1]
        updatedLeadsIds = data['updatedIndexList']

        # Updating stage of targeted lead
        movedToStage = LeadStage.objects.get(id=movedToStagePk)

        lead = get_object_or_404(Lead, id=lead_pk, is_deleted=False)
        if loggedInUser.company != lead.company:
            return HttpResponseForbidden()

        lead.stage = movedToStage
        lead.save()
        # print("Lead stage updated: ", lead.stage)

        # Updating order index of stage, from where the lead is moved
        movedFromStage = LeadStage.objects.get(id=movedFromStagePk)
        movedFromStage.leads_reorder_logic = \
            updatedLeadsIds['movedFromStageOrder']
        movedFromStage.save()
        print("movedFromStage updated: ", movedFromStage.leads_reorder_logic)

        # Updating order index of stage, to where the lead is moved
        movedToStage.leads_reorder_logic = updatedLeadsIds['movedToStageOrder']
        movedToStage.save()
        print("movedFromStage updated: ", movedToStage.leads_reorder_logic)

    return JsonResponse({"msg": "stage updated"})


@login_required(login_url='login')
def leadProfile(request, lead_pk):
    loggedInUser = get_object_or_404(
        UserProfile, user=request.user, is_deleted=False,)
    company = loggedInUser.company

    lead = get_object_or_404(Lead, id=lead_pk, is_deleted=False)
    # If lead doesn't belong to the company. send forbidden Error
    if lead.company != company:
        return HttpResponseForbidden()

    # For displaying stages in sorted order
    stages = LeadStage.objects.filter(company=company)
    stageReorderLogic = company.stage_reorder_logic
    sortedStages = sortQueryObj(stages, stageReorderLogic.split(','))

    leadLogs = LeadProfileLog.objects.filter(
        lead=lead_pk).order_by('-created_at')
    leadNotes = LeadNote.objects.filter(
        lead=lead_pk, is_deleted=False).order_by('-created_at')
    leadTasks = LeadTask.objects.filter(
        lead=lead_pk, is_deleted=False).order_by('-created_at')

    # print("orderIndexList: ", orderIndexList)

    context = {
        "loggedInUser": loggedInUser,
        "lead": lead,
        "leadLogs": leadLogs,
        "leadNotes": leadNotes,
        "leadTasks": leadTasks,
        "sortedStages": sortedStages,
        # "stageOrderIndexList": json.dumps(orderIndexList),
        "stageOrderIndexStr": stageReorderLogic,
    }
    return render(request, 'leads/lead_profile.html', context)


# Update Lead Profile
@login_required(login_url='login')
def updateLeadProfile(request, lead_pk):
    if request.method == 'POST':
        loggedInUser = get_object_or_404(
            UserProfile, user=request.user, is_deleted=False)

        lead = get_object_or_404(Lead, id=lead_pk, is_deleted=False)

        # If the user does not belong to the same company he is accessing
        if lead.company != loggedInUser.company:
            return HttpResponseForbidden()

        title = request.POST.get('lead_title')
        lead_stage = request.POST.get('lead_stage')
        contact_person = request.POST.get('contact_name')
        contact_email = request.POST.get('contact_email')
        phone = request.POST.get('contact_phone')
        designation = request.POST.get('designation')
        source = request.POST.get('source')

        # print("lead_stage: ", lead_stage, '-', type(lead_stage))

        if title:
            lead.title = title
            # Text for Lead Profile Log
            text = f"<i>{loggedInUser.full_name}</i>, updated the title of \
                lead to <b>{title}</b>"

        elif lead_stage:
            # print("stage updated")
            prevLeadStage = lead.stage
            updatedLeadStage = get_object_or_404(LeadStage, id=lead_stage)
            lead.stage = updatedLeadStage
            text = f"<i>{loggedInUser.full_name}</i>, updated the status \
                of the lead stage to <b>{updatedLeadStage.stage_label}</b>"

            # remove leadId to the updated StageElementIndexLogic
            prevStrLogicList = prevLeadStage.leads_reorder_logic.split(',')
            prevStrLogicList.remove(str(lead_pk))
            prevLeadStage.leads_reorder_logic = ','.join(prevStrLogicList)
            prevLeadStage.save()

            # Add lead_pk to the updated StageElementIndexLogic
            curStageLogicStr = updatedLeadStage.leads_reorder_logic
            if curStageLogicStr == '':
                updatedLeadStage.leads_reorder_logic = str(lead_pk)
            else:
                updatedLeadStage.leads_reorder_logic = \
                    f"{curStageLogicStr},{str(lead_pk)}"
            updatedLeadStage.save()

        elif contact_person:
            lead.contact_person = contact_person

templates/leads/add_lead.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Add Lead</title>
{% endblock title %}


{% block breadcrumb_heading %}
Add Lead
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="#">Add Lead</a>
</li>
{% endblock breadcrumb %}



{% block page_content %}

<div class="row">
    <div class="col-sm-12 col-lg-8 mx-auto">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="mb-0 text-white">New Lead Info</h4>
            </div>

            {% include 'partials/_flash_messages.html'%}

            <form action="" method="POST" enctype="multipart/form-data">

                {% csrf_token %}
                <div class="form-body">
                    <div class="card-body bg-light">
                        <div class="row pt-3 m-2">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_title">Title</label>
                                    {{form.title}}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_contact_person">Contact Person Name</label>
                                    {{form.contact_person}}
                                </div>
                            </div>


                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_email">Email</label>
                                    {{form.email}}
                                </div>
                            </div>


                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_phone">Phone</label>
                                    {{form.phone}}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_designation">Designation</label>
                                    {{form.designation}}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_stage">Stage</label>
                                    {{form.stage}}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="id_source">Source</label>
                                    {{form.source}}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="form-actions">
                    <div class="card-body">
                        <button type="submit" class="btn btn-success mx-4 mb-4 float-right">
                            <i class="fa fa-check"></i> SAVE
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- <div class="row mb-4">
    <div class="col-md-3 col-sm-12">
        <h4 class="card-title">With Progress</h4>
        <p>Indicates toast's progress.</p>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary" id="custom_progress-bar">Show
            Toast</button>
    </div>
</div> -->

{% endblock page_content %}

{% block custom_js %}
<script>
    // $(function () {
    //     // Success Type
    //     $('#ts-success').on('click', function () {
    //         toastr.success('Have fun storming the castle!', 'Miracle Max Says');
    //     });
    //     // Progress Bar
    //     $('#custom_progress-bar').on('click', function () {
    //         toastr.error('Something went wrong!',
    //             'Progress Bar', { "progressBar": true }
    //         );
    //     });
    // })

    // console.log(`status`, '{{status}}');
    // if ('{{status}}' == 400) {
    //     toastr.error('Please review all the fields and try again',
    //         'Something went wrong!', { "progressBar": true }
    //     );
    // }
</script>
{% endblock custom_js %}

templates/leads/leads_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Leads</title>
{% endblock title %}


{% block breadcrumb_heading %}
Leads
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="#">Leads</a>
</li>
{% endblock breadcrumb %}


{% block custom_css %}
<!-- Latest Sortable -->
<script src="https://raw.githack.com/SortableJS/Sortable/master/Sortable.js"></script>
<style>
    .ghost {
        opacity: .5;
        background-color: lightblue;
    }

    .custom_lead_card_class:hover {
        background-color: rgb(52, 52, 88) !important;
    }

    .custom_lead_title_class:hover {
        color: rgb(0, 0, 0) !important;
        font-weight: 700;
    }
</style>
{% endblock custom_css %}


{% block page_content %}


<!-- {% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %} -->


<div class="row mb-4">
    <div class="col-lg col-md">
        <a class="btn btn-rounded btn-outline-success float-right mx-2" href="{% url 'add_lead' %}">
            <i class="mdi mdi-account-plus"></i> Add a new Lead
        </a>
    </div>
</div>




<div class="row">
    <div class="col w-100">
        <div class="card overflow-auto">
            <div class="card-body">
                <div class="row flex-nowrap" style="min-height: 400px;">

                    {% for stageItem in sortedStages %}
                    <div class="col">
                        <div class="card" style="width: 15rem;">
                            <h5 class="card-header text-center bg-inverse text-white">{{stageItem.stage_label}}</h5>
                            <div class="card-body rounded px-0 stage_row"
                                id="{{stageItem.stage_label}}_{{stageItem.id}}">

                                <!-- {#% for leadItemkey, leadItemList in columnOrder.items %} -->

                                {% for leadItemkey, leadItemList in columnOrder %}

                                {% if leadItemkey == stageItem.stage_label %}
                                {% for leadItem in leadItemList %}
                                <div class="card bg-secondary rounded custom_lead_card_class" id="{{leadItem.id}}"
                                    style="cursor: pointer;">
                                    <div class="card-body w-100 text-center">
                                        <a href="{% url 'lead_profile' leadItem.id %}">
                                            <h4 class="my-0 text-white custom_lead_title_class">{{leadItem.title}}
                                                <span class="float-right">
                                                    <i class="ti-themify-favicon-alt text-primary" data-toggle="tooltip"
                                                        data-placement="top"
                                                        title="Hold and drag the card to change it's staus. OR, Click on the title to see the lead details"
                                                        data-original-title="Tooltip on top"></i>
                                                </span>
                                            </h4>
                                        </a>
                                        <p class="text-white mb-0">{{leadItem.contact_person}}</p>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</div>


{% endblock page_content %}

{% block custom_js %}
<script>
    // console.log(`object`, '{{messages.0}}');
    // if ('{{messages}}') {
    //     toastr.success('Form submitted successfully!!',
    //         'success!', { "progressBar": true }
    //     );
    // }
</script>
<script>
    const stage_row_class = document.getElementsByClassName('stage_row');
    // console.log(`stage_row_class: `, stage_row_class[0].id);

    //Collecting ids of all draggable card
    var arrElemId = [];
    for (let i = 0; i < stage_row_class.length; i++) {
        arrElemId.push(stage_row_class[i]);
    }

    // Function to get index of stages, from where the target lead is moved and to moved 
    function generateStrVal(childObj) {
        var strVal = '';
        var arr = [];
        for (var i = 0; i < childObj.length; i++) {
            arr.push(childObj[i].id);
        }
        return arr.join(',');
    }

    /* 
        Looping through all ids colleced of draggable cards and put them all 
        in same draggable class so that it can be dragged from one list to another list
    */

    for (let i = 0; i < arrElemId.length; i++) {
        Sortable.create(arrElemId[i], {
            group: 'shared',
            ghostClass: 'ghost',
            animation: 150,

            // Element dragging ended
            onEnd: function (event) {
                var itemElem = event.item;
                // dragged HTMLElement
                // console.log(`event.item`, event.item); // teaget item
                // console.log("target list: ", event.to.id);    // target list
                // console.log("previous list: ", event.from.id);  // previous list
                // console.log("element's old index within old parent: ", event.oldIndex);  // element's old index within old parent
                // console.log("element's new index within new parent: ", event.newIndex);  // element's new index within new parent
                // console.log("event.oldDraggableIndex: ", event.oldDraggableIndex); // element's old index within old parent, only counting draggable elements
                // console.log("event.newDraggableIndex: ", event.newDraggableIndex); // element's new index within new parent, only counting draggable elements
                // console.log(`event.from.children: `, event.from.children);
                // console.log(`event.to.children: `, event.to.children);


                var moved_from_stage = event.from.id;
                var moved_to_stage = event.to.id;
                var terget_lead_pk = event.item.id;
                // console.log(`moved_from_stage: `, moved_from_stage);
                // console.log(`moved_to_stage: `, moved_to_stage);
                // console.log(`terget_lead_pk: `, terget_lead_pk);

                var updatedIndexList = {
                    "movedFromStageOrder": generateStrVal(event.from.children),
                    "movedToStageOrder": generateStrVal(event.to.children),
                };
                // console.log('updatedIndexList: ', updatedIndexList);


                const url = '/lead/indexing/status/update/';
                fetch(url, {
                    method: "POST",
                    headers: {
                        'Content-Type': 'aplication/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        "moved_from_stage": moved_from_stage,
                        "moved_to_stage": moved_to_stage,
                        "terget_lead_pk": terget_lead_pk,
                        "updatedIndexList": updatedIndexList,
                    }),
                }).then(response => {
                    // console.log('Response: ', Response);
                    return response.json();
                }).then(data => {
                    // console.log('data: ', data);
                });
            },
        });
    }
</script>
{% endblock custom_js %}