crm_call/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('user_auth.urls')),
    path('',  include('leads.urls')),
    path('',  include('home.urls')),
    path('',  include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name="home"),
    path('setting/', views.companySetting, name="company_setting"),
    path('stage/add/', views.addStage, name="add_new_satge_for_leads"),
    path('stage/delete/<int:stage_pk>/', views.deleteStage,
         name="delete_stage"),
    path('stage-order/update/', views.updateStageOrder,
         name="update_stage_order"),
    path('move-stage-lead/', views.moveStageLead, name="move_stage_lead"),
    path('custom/field/create/', views.createCustomField,
         name="create_custom_field"),


    # API releted
    path('api/setting/', views.apiCompanySetting),
]

users/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('users/', views.getAllUser, name="get_all_user"),
    path('user/add/', views.addUser, name="add_user"),


    # path('user/<int:user_pk>/update/', views.updateUser, name="update_user"),
    path('user/<int:user_pk>/delete/', views.deleteUser, name="delete_user"),

    path('user/<int:user_pk>/password/update/',
         views.updateUserPassword, name="update_password"),

    path('user/<int:user_pk>/', views.userProfile, name="user_profile"),

]

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class Company(models.Model):
    super_admin = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True)

    company_name = models.CharField(max_length=200)
    api_key = models.CharField(max_length=50, default=uuid.uuid4())
    phone = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=50, blank=True)
    logo = models.ImageField(
        upload_to='company_logo/', default="default/dummy-logo.jpeg",)

    # to store logic for rendering the stage
    stage_reorder_logic = models.TextField(blank=True)

    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name


class UserProfile(models.Model):
    USERTYPE = (
        ('0', 'Super Admin'),
        ('1', 'Manager'),
        ('2', 'Normal User'),
        ('3', 'type-3'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    profile_pic = models.ImageField(
        upload_to='profile_pic/', default="default/profile-dum.jpg")

    user_type = models.CharField(max_length=50, choices=USERTYPE, blank=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.user.first_name:
            return self.user.first_name + ' ' + self.user.last_name
        return str(self.id)

    @property
    def full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfile


class AddUserForm1(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'last_name': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'email': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
        }


class AddUserForm2(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user_type']

        widgets = {
            'user_type': forms.Select(attrs={
                'class': "form-control",
            }),
        }


class UpdateUserForm1(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'is_active']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'last_name': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'email': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'is_active': forms.CheckboxInput(attrs={
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
        }

    # To disable the form fields in frontend(django won't look for it to update)
    def __init__(self, *args, **kwargs):
        super(UpdateUserForm1, self).__init__(*args, **kwargs)
        self.fields['email'].disabled = True

# class UserEditForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('username', 'first_name', 'last_name', 'email', 'password')

#     def __init__(self, *args, **kwargs):
#         super(UserEditForm, self).__init__(*args, **kwargs)
#         self.fields['username'].disabled = True
#         self.fields['email'].disabled = True


class UpdateUserForm2(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'profile_pic', 'user_type']
        widgets = {
            'phone': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
            'user_type': forms.Select(attrs={
                'class': "form-control",
                'autofocus': 'autofocus',
            }),
        }

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http.response import JsonResponse
from django.shortcuts import render, redirect

from .models import UserProfile
from . import forms

from .utils import userFormValidate, generateRandomPass, sendEmailInvtn


@login_required(login_url='login')
def getAllUser(request):
    user = request.user
    loggedInUser = UserProfile.objects.get(user=user)
    users = UserProfile.objects.filter(
        company=loggedInUser.company.id, is_deleted=False)

#     from django.core import serializers
#
#     # assuming obj is a model instance
#     serialized_obj = serializers.serialize('json', [user])
#     print(serialized_obj)

    context = {
        "loggedInUser": loggedInUser,
        "users": users,
    }
    return render(request, 'users/all_users.html', context)


@login_required(login_url='login')
def addUser(request):
    user = request.user
    loggedInUser = UserProfile.objects.get(user=user)
    company = loggedInUser.company

    form1 = forms.AddUserForm1()
    form2 = forms.AddUserForm2()
    context = {
        "loggedInUser": loggedInUser,
        "form1": form1,
        "form2": form2
    }

    if request.method == 'POST':
        context = {
            "loggedInUser": loggedInUser,
            "form1": form1,
            "form2": form2,
            'data': request.POST
        }
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        user_type = request.POST.get('user_type')
        password = generateRandomPass()

        validateForm = userFormValidate(
            email, first_name, last_name, user_type)

        if validateForm['error']:
            messages.add_message(request, messages.ERROR, validateForm['msg'])
            return render(request, 'users/add_user.html',
                          context, status=400)

        user = User.objects.create_user(username=email, email=email)
        user.set_password(password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        # Create a userprofile with user and agency
        UserProfile.objects.create(
            user=user, company=company, user_type=user_type)

        # print("neUserProfile: ", neUserProfile)

        # Send invitation mail to user email
        sendEmailInvtn(request, user, password)

        messages.add_message(
            request,
            messages.SUCCESS,
            'The Invitaion link has been sent to user.'
        )
        return render(request, 'users/add_user.html',
                      context, status=200)

    return render(request, 'users/add_user.html', context)


@login_required(login_url='login')
def userProfile(request, user_pk):
    user = request.user
    loggedInUser = UserProfile.objects.get(user=user)

    userProfile = UserProfile.objects.get(id=user_pk)
    if loggedInUser.company != userProfile.company:
        return JsonResponse({
            "status": "Error",
            "msg": "You are not authorized"
        })

    form1 = forms.UpdateUserForm1(instance=userProfile.user)  # user
    form2 = forms.UpdateUserForm2(instance=userProfile)  # UserProfile
    # Userprofile Agency Mapping
    # form3 = forms.AddUserForm2()

    context = {
        'form1': form1,
        'form2': form2,
        # "form3": form3,
        "userProfile": userProfile,
        "loggedInUser": loggedInUser,
    }
    if request.method == 'POST':
        # userStatus = request.POST['active_status']
        form1Data = forms.UpdateUserForm1(
            request.POST, instance=userProfile.user)
        form2Data = forms.UpdateUserForm2(
            request.POST, request.FILES, instance=userProfile)
        # form3Data = forms.AddInUserForm2(request.POST)

        print("form1 Data: ", form1Data)

        if form1Data.is_valid() and form2Data.is_valid():
            print("form is valid")
            form1Data.save()
            form2Data.save()
            # if userStatus == 'inactive':
            #     form1Data.is_active = False
            # form1Data.save()
            return redirect('user_profile', user_pk=user_pk)

    return render(request, 'users/user_profile.html', context)


@login_required(login_url='login')
def deleteUser(request, user_pk):
    userProfile = UserProfile.objects.get(id=user_pk)

    if request.method == 'POST':
        userProfile.is_deleted = True
        userProfile.save()
        # Set active status to false
        userProfile.user.is_active = False
        userProfile.user.save()
        return redirect('get_all_user')


# @login_required(login_url='login')
# def updateUser(request, user_pk):
#     loggedInUser = UserProfile.objects.get(user=request.user)
#     userProfile = UserProfile.objects.get(id=user_pk)
#     form1 = forms.UpdateUserForm1(instance=userProfile.user)
#     form2 = forms.UpdateUserForm2(instance=userProfile)
#     context = {
#         "loggedInUser": loggedInUser,
#         'form1': form1,
#         'form2': form2,
#         'userProfile': userProfile,
#     }
#
#     if request.method == 'POST':
#         form1 = forms.UpdateInUserForm1(
#             request.POST, instance=userProfile.user)
#         form2 = forms.UpdateInUserForm2(
#             request.POST, request.FILES, instance=userProfile)
#
#         print("form2 Data: ", form2)
#         if form1.is_valid() and form2.is_valid():
#             print("form is valid")
#             form1.save()
#             form2.save()
#             return redirect('/')
#     return render(request, 'users/update_user_details.html', context)


@login_required(login_url='login')
def updateUserPassword(request, user_pk):
    return JsonResponse({"msg": "hello"})

templates/users/add_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Add User</title>
{% endblock title %}

{% block breadcrumb_heading %}
Add User
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/users/">Users</a>
</li>
<li class="breadcrumb-item">
    <a href="#">Add User</a>
</li>
{% endblock breadcrumb %}


{% block page_content %}

<div class="row">
    <div class="col-sm-12 cl-md-8 col-lg-6 mx-auto">
        <div class="card">
            <div class="card-header bg-info">
                <h4 class="text-white text-center">Add a New User</h4>
            </div>

            <div class="card-body">
                <!-- For flash messages(Error/Succes messages) comming from backend -->
                {% include 'partials/_flash_messages.html'%}
                <div class="row">
                    <div class="col-sm-12">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="id_first_name">First Name</label>
                                        {{form1.first_name}}
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="id_last_name">Last Name</label>
                                        {{form1.last_name}}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="id_email">Email</label>
                                        {{form1.email}}
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="id_user_type">User Type</label>
                                        {{form2.user_type}}
                                    </div>
                                </div>
                            </div>

                            <!-- <button type="button" class="btn btn-dark">Cancel</button> -->
                            <button type="submit" class="btn btn-success mx-2 float-right">ADD USER</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    document.getElementById('id_first_name').classList.add('form-control');
    document.getElementById('id_last_name').classList.add('form-control');
    document.getElementById('id_email').classList.add('form-control');
    document.getElementById('id_user_type').classList.add('form-control');
</script> -->

{% endblock page_content %}

templates/users/all_users.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Users</title>
{% endblock title %}

{% block breadcrumb_heading %}
Users
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="#">Users</a>
</li>
{% endblock breadcrumb %}


{% block page_content %}



<div class="row mb-4">
    <div class="col-lg col-md">
        <a class="btn btn-rounded btn-outline-success float-right" href="{% url 'add_user' %}">
            <i class="mdi mdi-account-plus mr-1"></i> Add a new User
        </a>
    </div>
</div>


<div class="row">
    {% for item in users %}
    <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card pt-2 pl-2 bg-white">
            <div class="d-flex flex-row">
                <div class="p-2 ">
                    <a href="{% url 'user_profile' item.id %}" style="text-decoration: none;">
                        <div class="round align-self-center ">
                            <i class="ti-user"></i>
                        </div>
                    </a>
                </div>
                <a href="{% url 'user_profile' item.id %}" style="text-decoration: none;">
                    <div class="p-2">
                        <h2 class="text-info mb-0">{{item.full_name}}</h2>
                        <div>
                            <span class="text-muted">{{item.user.email}}</span>
                        </div>
                        <small>{{item.get_user_type_display}}</small>
                    </div>
                </a>
                <!-- <div class="align-self-center mr-3 ml-auto">
                    <h4 class="text-info mb-0">User Type</h4>
                </div> -->
            </div>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock page_content %}

templates/users/user_login_email.html
{% autoescape off%}

Hi {{user.username}}
please click this link below to join

http://{{domain}}{% url 'login' %}

Your password is {{password}}

{% endautoescape %}

templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>{{userProfile.full_name}}</title>
{% endblock title %}

{% block breadcrumb_heading %}
{{userProfile.full_name}}
{% endblock breadcrumb_heading %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/users/">Users</a>
</li>
<li class="breadcrumb-item">
    <a href="#">{{user.full_name}}</a>
</li>
{% endblock breadcrumb %}


{% block page_content %}

<div class="row">
    <div class="col-lg-8 col-xlg-6 col-sm-10 mx-auto">
        <div class="card">
            <div class="card-body">
                <center>
                    <img src="{{userProfile.profile_pic.url}}" class="rounded-circle" width="150">
                    <h4 class="card-title mt-2">{{userProfile.full_name}}</h4>
                    <h6 class="card-subtitle">{{userProfile.get_user_type_display}}</h6>
                </center>
            </div>
            <div>
                <hr>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4 col-xs-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">{{userProfile.phone}}</p>
                    </div>
                    <div class="col-md-4 col-xs-6 b-r">
                        <strong>Email</strong>
                        <br>
                        <p class="text-muted">{{userProfile.user.email}}</p>
                    </div>
                    <div class="col-md-4 col-xs-6">
                        <strong>User Type</strong>
                        <br>
                        <p class="text-muted">{{userProfile.get_user_type_display}}</p>
                    </div>
                </div>
            </div>

            <div class="card-footer p-4 ">
                <div class="row d-flex justify-content-around">
                    <div class="col-lg col-md d-flex justify-content-center">
                        <button class="btn btn-rounded btn-outline-warning" data-toggle="modal"
                            data-target="#verticalcenter_update_in_user">
                            <i class="fas fa-edit"></i>Update this user
                        </button>
                    </div>

                    <div class="col-lg col-md d-flex justify-content-center">
                        <button class="btn btn-rounded btn-outline-danger" data-toggle="modal"
                            data-target="#verticalcenter_delete_in_user">
                            <i class="mdi mdi-delete-forever"></i>Delete this user
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



<!-- Delete Client button modal content -->
<div id="verticalcenter_delete_in_user" class="modal" tabindex="-1" role="dialog" aria-labelledby="vcenter"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h3 class="modal-title font-weight-bold" id="vcenter" style="color: rgb(207, 33, 33);">
                    Warning!!</h3>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <p>
                    Are you sure, you want to delete User <strong><i> "{{userProfile.full_name}}" </i></strong>?
                </p>
            </div>

            <div class="modal-footer">

                <button type="button" class="btn btn-warning waves-effect float-left"
                    data-dismiss="modal">Cancel</button>

                <form action="{% url 'delete_user' userProfile.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger waves-effect float-right">Confirm</button>
                </form>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal content -->




<!-- Update Client Details button modal content -->
<div id="verticalcenter_update_in_user" class="modal" tabindex="-1" role="dialog" aria-labelledby="vcenter"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center bg-dark text-white">
                <h3 class="modal-title font-weight-bold" id="vcenter">Update User Details</h3>
                <button type="button" class="close text-white" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form action="" method="post" enctype="multipart/form-data" class="form-horizontal form-material">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6 form-group">
                            <label for="id_first_name" class="col-md-12">First Name</label>
                            <div class="col-md-12">
                                {{form1.first_name}}
                            </div>
                        </div>

                        <div class="col-6 form-group">
                            <label for="id_last_name" class="col-md-12">Last Name</label>
                            <div class="col-md-12">
                                {{form1.last_name}}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-6 form-group">
                            <label for="id_email" class="col-md-12">Email </label>
                            <div class="col-md-12">
                                {{form1.email}}
                            </div>
                        </div>

                        <div class="col-6 form-group">
                            <label for="id_phone" class="col-md-12">Phone</label>
                            <div class="col-md-12">
                                {{form2.phone}}
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-6 form-group">
                            <label for="id_user_type" class="col-md-12">User Type </label>
                            <div class="col-md-12">
                                {{form2.user_type}}
                            </div>
                        </div>
                        <div class="col-6 form-group">
                            <label for="id_active_status">Active status</label>
                            {{form1.is_active}}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 form-group">
                            <label for="id_profile_pic" class="col-md-12">Profile Pic
                                <span>
                                    <img src="{{userProfile.profile_pic.url}}" class="rounded-circle" width="50">
                                </span>
                            </label>

                            <div class="col-md-12">
                                <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic"
                                    class="form-control">
                            </div>
                        </div>
                    </div>




                    <!-- footer submit button -->

                    <div class="form-group d-flex justify-content-around text-center">
                        <div class="col-sm-6">
                            <button type="button" class="btn btn-warning waves-effect"
                                data-dismiss="modal">Cancel</button>
                        </div>
                        <div class="col-sm-6">
                            <button class="btn btn-success waves-effect">
                                <i class="mdi mdi-account-edit"></i>
                                <span> Update Profile </span>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal content -->


{% endblock page_content %}