crm_call/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('user_auth.urls')),
    path('',  include('leads.urls')),
    path('',  include('home.urls')),
    path('',  include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name="home"),
    path('setting/', views.companySetting, name="company_setting"),
    path('stage/add/', views.addStage, name="add_new_satge_for_leads"),
    path('stage/delete/<int:stage_pk>/', views.deleteStage,
         name="delete_stage"),
    path('stage-order/update/', views.updateStageOrder,
         name="update_stage_order"),
    path('move-stage-lead/', views.moveStageLead, name="move_stage_lead"),
    path('custom/field/create/', views.createCustomField,
         name="create_custom_field"),


    # API releted
    path('api/setting/', views.apiCompanySetting),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Company


class LeadStage(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    stage_label = models.CharField(max_length=50)

    # to store logic, for rendering the leads in the stage
    leads_reorder_logic = models.TextField(blank=True)

    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.stage_label


class CustomField(models.Model):
    FIELD_TYPE = (
        ('text', 'Text'),
        ('number', 'Number'),
        ('email', 'Email'),
        ('drop_down', 'Drop Down'),
        ('radio', 'Radio'),
        ('date', 'Date'),
        ('time', 'Time'),
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    field_title = models.CharField(max_length=50)
    field_type = models.CharField(
        max_length=50, choices=FIELD_TYPE, default="Text")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.field_title


class CustomFieldChoise(models.Model):
    custom_field = models.ForeignKey(CustomField, on_delete=models.CASCADE)
    choise_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.choise_name


# For storing gmail credential
class GmailCredential(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=200, null=True)
    refresh_token = models.CharField(max_length=200, null=True)
    token_uri = models.CharField(max_length=200, null=True)
    client_id = models.CharField(max_length=200, null=True)
    client_secret = models.CharField(max_length=200, null=True)
    id_token = models.CharField(max_length=200, null=True)
    scopes = models.CharField(max_length=1000, null=True)
    expiry = models.DateTimeField(blank=True, null=True)
    valid = models.BooleanField(default=True)

home/forms.py
from home.models import CustomField
from django import forms


class AddCustomFieldForm(forms.ModelForm):
    class Meta:
        model = CustomField
        fields = ['field_title', 'field_type']

        widgets = {
            'field_title': forms.TextInput(attrs={
                'type': 'text',
                'class': "form-control",
            }),
            'field_type': forms.Select(attrs={
                'class': "form-control",
            }),
        }

home/views.py
import json
import uuid

from django.core.serializers import serialize
from django.http.response import HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.models import User

from leads.models import Lead
from users.models import Company, UserProfile

from .forms import AddCustomFieldForm
from .models import CustomField, CustomFieldChoise, LeadStage
# from .gmail_api import syncGmailAPI
from .utils import sortQueryObj


@login_required(login_url='login')
def homePage(request, api_key=None):
    user = request.user
    loggedInUser = UserProfile.objects.get(user=user)

    # service = syncGmailAPI(user)
    # print("credssss: ", service)
    randomStr = uuid.uuid4()
    print("randomStr: ", len(str(randomStr)), '-', randomStr)
    context = {
        "loggedInUser": loggedInUser,
    }
    return render(request, 'home/home_page.html', context)


@login_required(login_url='login')
def companySetting(request):
    loggedInUser = UserProfile.objects.get(user=request.user)
    company = loggedInUser.company
    stages = LeadStage.objects.filter(company=company)

    # orderIndexObj, created = StageIndexOrder.objects.get_or_create(
    #     company=company)

    # orderIndexList = []
    # if not created:
    #     orderIndexList = orderIndexObj.reorder_string.split(',')
    # sortedStages = sortQueryObj(stages, orderIndexList)

    stageReorderLogic = company.stage_reorder_logic
    # print("stageReorderLogic: ", stageReorderLogic)
    if stageReorderLogic.strip() != '':
        sortedStages = sortQueryObj(stages, stageReorderLogic.split(','))
    else:
        sortedStages = []

    # print("sortedStages: ", sortedStages)

    customFields = CustomField.objects.filter(company=company)

    context = {
        "sortedStages": sortedStages,
        "loggedInUser": loggedInUser,
        "custom_field_form": AddCustomFieldForm(),
        "customFields": customFields,
    }
    return render(request, 'home/company_setting_page.html', context)


# Adding stages for lead in company setting page
@login_required(login_url='login')
def addStage(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        newStageObj = LeadStage.objects.create(
            company=company,
            stage_label=request.POST['new_lead_stage'],
            added_by=request.user,
        )

        stageReorderLogic = company.stage_reorder_logic
        if stageReorderLogic.strip() == '':
            company.stage_reorder_logic = str(newStageObj.id)
        else:
            company.stage_reorder_logic = f"{stageReorderLogic},{str(newStageObj.id)}"
        company.save()

        return redirect('company_setting')


# Updating order of stages in company setting page whem dragged
@login_required(login_url='login')
def updateStageOrder(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        stageReorderLogic = company.stage_reorder_logic

        data = json.loads(request.body)
        draggedItemId = data['draggedItemId']
        oldIndexItem = data['oldIndexItem']
        newIndexItem = data['newIndexItem']

        # Split string by comma
        orderList = stageReorderLogic.split(',')
        # print("orderList1: ", orderList)

        # Delete old index of dragged element
        del orderList[oldIndexItem]
        # print("orderList2: ", orderList)

        # Add dragged element to new index
        orderList.insert(newIndexItem, draggedItemId)
        # print("orderList3: ", orderList)
        newStr = ",".join(orderList)
        # print("new str: ", newStr)

        company.stage_reorder_logic = newStr
        company.save()

        return JsonResponse({"msg": "success"})


# Delete stage from settings if there is no leads in the stage
@login_required(login_url='login')
def deleteStage(request, stage_pk):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        company = loggedInUser.company
        stageReorderLogic = company.stage_reorder_logic

        stage = get_object_or_404(LeadStage, id=stage_pk)
        if company != stage.company:
            return HttpResponseForbidden()

        leadsReorderLogic = stage.leads_reorder_logic

        # check, if there is any leads in this stage
        if leadsReorderLogic.strip() == '':
            stage.delete()

            logicOrderStrList = stageReorderLogic.split(',')
            # print("logicOrderStrList: ", logicOrderStrList)

            logicOrderStrList.remove(str(stage_pk))
            # print(logicOrderStrList)

            newStageReorderLogic = ",".join(logicOrderStrList)
            # print("newStrOrder: ", newStrOrder)

            company.stage_reorder_logic = newStageReorderLogic
            company.save()

            return JsonResponse({
                "success": True,
                "msg": "Successfully deleted!!",
            })
        else:
            return JsonResponse({
                "success": False,
                "msg": "Can't delete this stage. Please move all the leads" +
                " inside of this stage and try again."
            })


# Move leads from one stage to another stage
@login_required(login_url='login')
def moveStageLead(request):
    if request.method == 'POST':
        company = UserProfile.objects.get(user=request.user).company

        movedFrom = request.POST.get('stage_moved_from')
        movedTo = request.POST.get('stage_moved_to')
        # print(movedFrom, '-', movedTo)

        movedFromStage = LeadStage.objects.get(id=movedFrom)
        # Update status of all the leads which are moved
        movedToStage = LeadStage.objects.get(id=movedTo)
        # print(newStage.stage_label)

        if company != movedFromStage.company:
            return HttpResponseForbidden()

        movedFromLeadIds = movedFromStage.leads_reorder_logic
        movedToLeadIds = movedToStage.leads_reorder_logic

        # print(movedFromLeadIds, '-', movedToLeadIds)

        if movedFromLeadIds.strip() != '':
            leadIds = movedFromLeadIds.split(',')
            # print("leadIds: ", leadIds)

            for leadId in leadIds:
                newLead = get_object_or_404(Lead, id=leadId)
                newLead.stage = movedToStage
                newLead.save()
                # print("lead updated: ", newLead.stage.stage_label)
        else:
            return redirect('company_setting')

        # Move the order indexing from movedFrom to movedTo .
        if movedToLeadIds == '':
            movedToStage.leads_reorder_logic = movedFromLeadIds
        else:
            movedToStage.leads_reorder_logic = f"{movedToLeadIds},{movedFromLeadIds}"
        movedToStage.save()

        # empty the logic order of MovedFrom
        movedFromStage.leads_reorder_logic = ''
        movedFromStage.save()

        return redirect('company_setting')


@login_required(login_url='login')
def createCustomField(request):
    if request.method == 'POST':
        loggedInUser = UserProfile.objects.get(user=request.user)
        print(request.POST)
        extra_field_size = len(request.POST)-3
        print("extra_field_size: ", extra_field_size)

        if request.POST.get('field_type') == 'drop_down' or (
                request.POST.get('field_type') == 'drop_down'):
            if(extra_field_size <= 0):
                return redirect('company_setting')

        form = AddCustomFieldForm(request.POST)
        if form.is_valid():
            print("form Valid")
            customFieldObj = form.save(commit=False)
            customFieldObj.company = loggedInUser.company
            customFieldObj.save()

            if extra_field_size > 0:
                for index in range(extra_field_size):
                    option_choise = request.POST.get(f"option_{index}")
                    if option_choise:
                        CustomFieldChoise.objects.create(
                            custom_field=customFieldObj,
                            choise_name=option_choise,
                        )

        return redirect('company_setting')


# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
# ------------------------------------------APIS-----------------------------------------
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
def apiCompanySetting(request):
    api_key = request.GET.get('key')
    # print(api_key)

    if not api_key or len(api_key) < 36:
        return JsonResponse({
            "success": False,
            "msg": "Api Key is missing or invalid",
        }, status=400)

    try:
        company = Company.objects.get(api_key=api_key)
    except Company.DoesNotExist:
        return JsonResponse({
            "success": False,
            "msg": "invalid Key",
        }, status=404)

    stages = LeadStage.objects.filter(company=company)

    stageReorderLogic = company.stage_reorder_logic
    # print("stageReorderLogic: ", stageReorderLogic)
    if stageReorderLogic.strip() != '':
        sortedStages = sortQueryObj(stages, stageReorderLogic.split(','))
    else:
        sortedStages = []

    return JsonResponse({
        "success": True,
        "key": api_key,
        "stage": serialize('json', sortedStages)
    })

templates/home/home_comp/custom_fields.html
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title text-center">Custom Fields</div>
            </div>
            <!-- Create a Custom Field -->
            <div class="card-body">

                <div class="row mb-4">
                    <div class="col-lg col-md">
                        <button class="btn btn-rounded waves-effect waves-light btn-outline-success py-2 float-right"
                            data-toggle="modal" data-target="#create_custom_field_modal">
                            <i class="mdi mdi-plus"></i> Create a Custom Field
                        </button>

                        <!-- Create a Custom Field modal content -->
                        <div id="create_custom_field_modal" class="modal" tabindex="-1" role="dialog"
                            aria-labelledby="vcenter" aria-hidden="true" style="display: none;">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header text-white bg-primary">
                                        <h2>Create a Custom Field</h2>
                                        <button type="button" class="close text-warning" data-dismiss="modal"
                                            aria-hidden="true">×</button>
                                    </div>

                                    <div class="modal-body">
                                        <form action="{% url 'create_custom_field' %}" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label for="id_field_title" class="control-label">Field Title:</label>
                                                {{custom_field_form.field_title}}
                                            </div>

                                            <div class="form-group">
                                                <label for="id_field_type" class="control-label">Field Type:</label>
                                                {{custom_field_form.field_type}}
                                            </div>
                                            <div class="form-group" id="custon_field_extra_option">


                                            </div>



                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default waves-effect"
                                                    data-dismiss="modal">Close</button>
                                                <button type="submit"
                                                    class="btn btn-danger waves-effect waves-light">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.modal -->
                    </div>

                </div>


                <div class="row">
                    <div class="col-12">
                        <ul>
                            {% for customField in customFields %}
                            <li> Field Name: <b>{{customField.field_title}}</b>, Field Type:
                                <b>{{customField.get_field_type_display}}</b>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // console.log(`selectedFieldType: `, selectedFieldType);

    var count = 0;
    $('#id_field_type').change(function () {
        const selectedFieldType = $('#id_field_type').find(":selected").text();
        const selectedFieldTypeValue = $('#id_field_type').val();
        console.log(`selectedFieldVal: `, selectedFieldTypeValue);
        if (selectedFieldTypeValue == "drop_down" || selectedFieldTypeValue == "radio") {
            // alert(selectedFieldTypeValue)
            $('#custon_field_extra_option').children().remove();
            $('#custon_field_extra_option').append(`
                <div class="card px-3">
                    <div class="card-body p-0" id="extra_field_card_body">
                        <label class="control-label" for="option_${count}">Add Options for ${selectedFieldType}</label>
                        <input type="text" class="form-control my-1" name="option_${count}" required id="option-id_${count}" />
                    </div>
                    <div class="card-footer px-0">
                        <button class="btn btn-info" onclick="addInputField(this)">Add More Option</button>
                    </div>
                </div>
            `);
            count++;
        }
    });

    function addInputField(item) {
        console.log(count);
        let hasError = false
        for (let i = 0; i < count; i++) {
            var curFieldVal = $(`#option-id_${i}`).val();
            if (curFieldVal.trim().length <= 0) {
                hasError = true;
                break;
            }
        }

        if (hasError == false) {
            $('#extra_field_card_body').append(`
                <input type="text" class="form-control my-1" name="option_${count}" required id="option-id_${count}" />
            `);
            count++;
        } else {
            // alert("Option field can't be blank");
            toastr.error("Option Field shouldn't be blank!!",
                'Error!', { "progressBar": true }
            );
        }
    }
</script>

templates/home/home_comp/dashboard_mail.html
{% load static %}



{% if not gmail_cred %}
<button data-toggle="modal" data-target="#send_email_to_profile_user" class="btn rounded btn-success float-right mx-2">
    <i class="far fa-envelope mr-1"></i> Send Email
</button>
{% else %}
<form method="post" action="{#% url 'sync_with_gmail' %}">
    {% csrf_token %}
    <input type="submit" name="authorise" value="Sync With Gmail" class="btn btn-info float-right mx-2">
</form>
{% endif %}

<!--send Email button modal content -->
<div id="send_email_to_profile_user" class="modal bs-example-modal-lg" tabindex="-1" role="dialog"
    aria-labelledby="vcenter" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center bg-primary">
                <h3 class="modal-title font-weight-bold text-white" id="vcenter">
                    Update Your Portfolio</h3>
                <button type="button" class="custom_icon_class close text-warning" data-dismiss="modal"
                    aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form action="{#% url 'send_email_to_profile' userProfile.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <input type="email" id="example-email" name="email-to" class="form-control"
                                    placeholder="To">
                            </div>

                            <div class="form-group">
                                <input type="text" id="example-subject" name="email-subject" class="form-control"
                                    placeholder="Subject">
                            </div>

                            <div id="summernote"></div>

                        </div>
                    </div>


                    <div class="modal-footer">
                        <button class="btn btn-dark" data-dismiss="modal" id="discard-compose">Discard</button>
                        <button class="btn btn-success waves-light float-right" onclick="sendMail(event)">
                            <i class="far fa-envelope"></i> Send
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.modal content -->


{% block custom_js %}
<script>
    $(document).ready(function () {
        $('#summernote').summernote({
            placeholder: 'Type your email Here',
            tabsize: 2,
            height: 300,
            followingToolbar: false
        });
    });
</script>
{% endblock custom_js %}

templates/home/home_comp/move_stage_card.html
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title text-center">Move Leads from one stage to another</h4>
            </div>

            <div class="card-body">
                <form action="{% url 'move_stage_lead' %}" method="POST">
                    {% csrf_token %}

                    <div class="row mb-4">
                        <div class="form-group col-4">
                            <label class="" for="stage_moved_from">Move From</label>
                            <select class="custom-select mr-sm-2" name="stage_moved_from" id="stage_moved_from">
                                <option selected="">Choose...</option>
                                {% for stage in sortedStages %}
                                <option value="{{stage.id}}">{{stage.stage_label}}</option>
                                {% endfor %}

                            </select>
                        </div>

                        <div class="form-group col-4">
                            <label class="" for="stage_mpved_to">Move To</label>
                            <select class="custom-select mr-sm-2" name="stage_moved_to" id="stage_mpved_to">
                                <option selected="">Choose...</option>
                                {% for stage in sortedStages %}
                                <option value="{{stage.id}}">{{stage.stage_label}}</option>
                                {% endfor %}
                            </select>

                        </div>
                        <div class="form-group mt-4">
                            <button type="submit" class="btn btn-success waves-effect mx-2 mt-1">Confirm</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>